### PR TITLE
#26:Using host network for execution of exasclt

### PR DESCRIPTION
**Pull request by tomuben**
In case of "exasclt upload", the user might try to push image to a database running in another docker instance on the host. For that we need to execute the exasclt docker instance in the host network, not the isolated docker network.

Also, execute tests within container, by using exaslct script instead of starter_scripts/exaslct_without_poetry.sh

### CODE REVIEW

**Comment by tkilias** [comment]
Explanation isn't really correct. The main issue is if you run a docker-db on the same machine as exaslct and try to upload a language container to the docker-db. Everything else, should actually work without to much hassle. The only other problem I can imagine are some crazy firewall settings which somehow don't like exaslct being in a docker network. If something, like that should exist, using host network should solve it, too.

**Review by tkilias — COMMENTED** [review]
see last comment

**Comment by tkilias** [comment]
### 1. We need to investigate the following error:

https://github.com/exasol/script-languages-container-tool/pull/36/checks?check_run_id=2777400123#step:6:6148

It seems we are missing the output from exaslct, so this might need a fix in the integration-test-environment or an update.

```
Traceback (most recent call last):
  File "/home/runner/work/script-languages-container-tool/script-languages-container-tool/test/test_run_db_test_docker_pass_through.py", line 23, in test_docker_test_environment
    self.test_environment.run_command(command, track_task_dependencies=True)
  File "/home/runner/.cache/pypoetry/virtualenvs/exasol-script-languages-container-tool-GJpOVBJH-py3.6/src/exasol-integration-test-docker-environment/exasol_integration_test_docker_environment/test/utils.py", line 121, in run_command
    print(e.stdout.decode("UTF-8"))
AttributeError: 'NoneType' object has no attribute 'decode'
```

### 2. Then we also need to check the following warning, might be not related to your changes, if that's the case, please open a ticket.

https://github.com/exasol/script-languages-container-tool/pull/36/checks?check_run_id=2777400123#step:6:4662

```
......./usr/local/lib/python3.6/dist-packages/luigi/parameter.py:279: UserWarning: Parameter "path_in_bucket" with value "None" is not of type string.
  warnings.warn('Parameter "{}" with value "{}" is not of type string.'.format(param_name, param_value))
```

###  3. And, I have the feeling we need buffered output for the tests or should switch to pytest, because it usually has better output and can work with the existing tests.

**Comment by tomuben** [comment]
> Explanation isn't really correct. The main issue is if you run a docker-db on the same machine as exaslct and try to upload a language container to the docker-db. Everything else, should actually work without to much hassle. The only other problem I can imagine are some crazy firewall settings which somehow don't like exaslct being in a docker network. If something, like that should exist, using host network should solve it, too.

I updated the description

**Comment by tomuben** [comment]
It would be good to get a summary of the test result with a filter for some keywords (warning/error/...) from the CI build....

**Comment by tomuben** [comment]
> ### 2. Then we also need to check the following warning, might be not related to your changes, if that's the case, please open a ticket.
> https://github.com/exasol/script-languages-container-tool/pull/36/checks?check_run_id=2777400123#step:6:4662
> 
> ```
> ......./usr/local/lib/python3.6/dist-packages/luigi/parameter.py:279: UserWarning: Parameter "path_in_bucket" with value "None" is not of type string.
>   warnings.warn('Parameter "{}" with value "{}" is not of type string.'.format(param_name, param_value))
> ```
> 

This warning is caused by the unit test: 
``` 
test_docker_upload_without_path_in_bucket
```

I guess, as the name says, this behavior is explicitly tested. I guess we can ignore. @tkilias  f.y.i.

**Pull request merged**
